# -*- coding: utf-8 -*-
"""aprilStream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LM2rY8Lck1PGVBXI4L4QyawA7rOc3o6q
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df=pd.read_csv("Advertising.csv")
st.title("Advertising Effectivenes Alex Girum")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X axis",["TV","radio","newspaper"])
y_var=st.sidebar.selectbox("Y axis",["sales"])

#show scatter plot
fig=px.scatter(df,x=x_var,y=y_var)
st.plotly_chart(fig)


#Dataframe
st.write("###This is the data")
st.dataframe(df)

#show map
st.title("I'm the map!!!")
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',size='newspaper',
                      hover_name='City',color='sales',
                      color_continuous_scale=px.colors.sequential.Viridis)
fig.update_layout(mapbox_style='carto-positron')
st.plotly_chart(fig)